### ISSUE TITLE
§-filtteröinti ja tidy_time = TRUE

### ISSUE THREAD

**Issue by jalasalmi** [robonomist/robonomistClient#1]
§-filtteröinti vaatii, että tietää kolumnien järjestyksen. Parametrivalinta tidy_time = TRUE kuitenkin muuttaa kolumnien järjestystä: 

```
robonomistClient::data("StatFin/asu/asvu/statfin_asvu_pxt_11x4.px§§Koko maa")

robonomistClient::data("StatFin/asu/asvu/statfin_asvu_pxt_11x4.px§§Koko maa", tidy_time = TRUE)

```

**Comment by itkonen** [comment]
Tämän on (valitettavasti) ominaisuus eli §-filtteröinti tapahtuu aina sarakkeiden sijainnin perusteella ja ´tidy_time´ saattaa muuttaa sijainteja. Sarakkeen sijainnista riippumattoman filtteröinnin saa varmasti kirjoittamalla filtteri-lausekkeen auki eli:
```
robonomistClient::data("StatFin/asu/asvu/statfin_asvu_pxt_11x4.px", tidy_time = TRUE) |> filter(Alue == "Koko maa")
```
