### ISSUE TITLE
Datapyyntö: Öljyn hinta

### ISSUE THREAD

**Issue by jhuovari** [robonomist/robonomistClient#12]
Ainakin EIA tarjoa öljyn hintadatoja avoimena. Viikkodata olisi hyvä. Siellä on myös päivädataa, mutta julkaisu on kai kerran viikossa, niin ei meidän tarve ole tiuhempaan.

https://www.eia.gov/opendata/

Siellä on toki muutakin mielenkiintoista lähinnä liittyen tuotantoon, ulkomaankauppaa ja kv-dataa myös energiasta, mutta öljyn hinta olisi hyvä saada jostain. Kuukausisarjan saa ECB:stä, mutta kuukausi on välillä vähän turhan hidas.

**Comment by itkonen** [comment]
Serverin uuteen versioon tulee EIA ja FRED. Niistä löytyy paljon dataa näihin tarpeisiin. Päivitän sen teille huomiseksi. 

`data_get`-funktiolla pääsee hakemaan dataa suoraan aikasarjatunnuksilla tyyliin: `data_get("fred/DCOILBRENTEU")`

**Comment by itkonen** [comment]
Jes, pistin teidän palvelimen päivittymään. Siinä menee muutama minuutti. Esimerkkejä uusien datalähteiden käytöstä löytyy [täältä](https://robonomist.github.io/robonomistClient/articles/special.html).

**Comment by jhuovari** [comment]
Vau, kiitoksia. Tuo FRED on loistava lisäys.
