### ISSUE TITLE
ECB tiedoissa time NA

### ISSUE THREAD

**Issue by jhuovari** [robonomist/robonomistClient#13]
Haku:
```
data_get("ecb/EST", dl_filter = "B.EU000A2X2A25.WT")
```
Tuottaa pelkkää NA:ta time sarakkeelle. En ole törmännyt samaan muissa ecb-tauluissa.

**Comment by itkonen** [comment]
Tämän pitäisi toimia nyt. Taulukossa oli erikoinen frekvenssimerkintä, jota ohjelma ei osannut tulkita.
