### ISSUE TITLE
oecd/ECO_TRACKER3 antaa vain virheen

### ISSUE THREAD

**Issue by jhuovari** [robonomist/robonomistClient#14]
```
data("oecd/ECO_TRACKER3")
```
√ Requesting data [159ms]
Error in UseMethod("select") : 
  no applicable method for 'select' applied to an object of class "NULL"

`data("oecd/")` sen kuitenkin löytää

**Comment by itkonen** [comment]
Vika on korjattu ja nyt pitäisi toimia taas. Tässä oli datalähteellä jännä bugi, että OECD:n taulukossa aikaulottuvuus oli rikki. Siksi tähän tauluun ei saa aikaa automaattisesti parsittua. Tästä voidaan helposti tehdä erillinen tidy-taulu, jos on tarpeen.

**Comment by itkonen** [comment]
Tuo onkin hieman hankalasti siistittävä taulukko, joten tein siitä siistityn version: `data("tidy/ECO_TRACKER3")` Tämä näkyy teidän palvelimella viimeistään huomenna aamulla.

**Comment by jhuovari** [comment]
Nyt toi tidy/ECO_TRACKER3 ei enää toimi, ja taulu löytyy myös versioina oecd/ ja oecd3/. Mitä on syytä käyttää?

**Comment by itkonen** [comment]
Se sekosi OECD:n rajapinnan myötä, mutta nyt se taas toimii. OECD selvittää parhaillaan, mistä heidän palvelimen epävakaus johtuu.

**Comment by jhuovari** [comment]
Ei toi tidy ainakaan mulla toimi. Antaa vaan request failed.

**Comment by itkonen** [comment]
Pahoittelut, nyt se toimii myös teidän palvelimella.
