### ISSUE TITLE
Luken tidy_time tiedoissa toinen virhe

### ISSUE THREAD

**Issue by jhuovari** [robonomist/robonomistClient#15]
```
data_get("luke/02_Maatalous/04_Tuotanto/22_Kaytossa_oleva_maatalousmaa/03_Peltoala_1910_ja_1920-.px", tidy_time = T) |> tail()
```
Antaa tiedot vain vuoteen 2012 asti. Siellä näyttäisi olevan alaviite vuodessa 2013, joten katkaisee siitä.
Poikkeaa nähdäkseni #11 virheestä.

**Comment by itkonen** [comment]
Tässäkin on samantyyppinen virhe Luken px-tiedostossa. Ja edellinenkin virhe on yhä korjaamatta. Pitää vähän kuumotella heitä. Jos ongelmaa ei saada korjattua datan alkulähteellä, niin meidän pitää rakentaa kiertotie tai laadunvarmistustyökalu, joka varoittaa epäluotettavasta datasta.

**Comment by itkonen** [comment]
Nyt Luke on korjannut nämäkin tiedot.
