### ISSUE TITLE
Datapyyntö FAO

### ISSUE THREAD

**Issue by jhuovari** [robonomist/robonomistClient#16]
Onnistuisiko FAO:n lisääminen
https://www.fao.org/faostat/en/#home

**Comment by itkonen** [comment]
Joo, nämä on mahdollista lisätä. Näyttäisi, ettei ole kovinkaan hankala.

**Comment by itkonen** [comment]
Nyt löytyy FAO:n datat tietokannasta: `data("fao/")`
