### ISSUE TITLE
unctad tidy_time ei toimi

### ISSUE THREAD

**Issue by jhuovari** [robonomist/robonomistClient#17]
```
data_get("unctad/US_CommodityPrice_M", tidy_time = TRUE) |> str()
```
Tiedoissa alkuperäinen Period ei time

@itkonen

**Comment by itkonen** [comment]
Tein seuraavaan versioon heuristisen funktion, joka yrittää parsia aikamuuttujan siistiksi. Valitettavasti datalähdeessä talukot eivät sisällä täsmällistä tietoa aikaulottuvuudesta ja lähdedata on muutenkin varsin heterogeenista. Jos näiden datojen siistiminen pidemmälle on tarpeen, siihen pitäisi varata pari työpäivää.

**Comment by jhuovari** [comment]
OK, kuvien piirtämisessä ei suuri ongelma, koska ne voi aina parsia taulukkkokohtaisesti, mutta ennustedatojen haku ei toimi ilman. 
Luultavasti sieltä tarvitaan vain unctad/US_CommodityPrice_M-taulua.

**Comment by itkonen** [comment]
Tein putsatun version tästä taulukosta: 
`data("tidy/US_CommodityPrice_M")`

**Comment by jhuovari** [comment]
Tuossa tidy:ssa on vielä CommodityProduct Label ja CommodityProduct, joka on siis edellisen koodi. 
pttrobo::yaml_to_excel() kertaa haetut tiedot, jos kumpikin mukana.

**Comment by jhuovari** [comment]
Ongelma tästä ratkesi tällä: https://github.com/pttry/pttrobo/issues/14
