### ISSUE TITLE
Eurostat on alkanut puhua saksaa

### ISSUE THREAD

**Issue by jhuovari** [robonomist/robonomistClient#18]
Haut eurostatista ilman kielimääritystä tuovat nyt saksankielisen version.

**Comment by itkonen** [comment]
Entschuldigung! Päivityksen yhteydessä oletuskieli oli mennyt sekaisin. Nyt se on korjattu!

**Comment by itkonen** [comment]
Rajapinnan on siis tarkoitus toimia niin, että kun kieltä ei määritetä, data tulee datalähteen oletuskielellä. Eurostatin tapauksessa se on englanti. Muut kielet saa sitten `lang`-parametrilla, esim. `data("eurostat/aact_uv01", lang = "de")`

Datalähteiden kielivaihtoehdot näkee komennolla `View(datasources())` ja listassa ensimmäinen kieli on kunkin datalähteen oletuskieli.
