### ISSUE TITLE
Luken taulussa tidy_time = TRUE ei toimi

### ISSUE THREAD

**Issue by jhuovari** [robonomist/robonomistClient#2]
Jostain syystä:
`data_get("luke/02_Maatalous/06_Talous/02_Maataloustuotteiden_tuottajahinnat/08_Tuottajahinnat_Vilja_rypsi_rapsi_v.px", tidy_time = TRUE)`
ei muunna vuotta Date-muotoon. En ole törmännyt samaan ongelmaa muiden Luken taulujen kanssa.

**Comment by jhuovari** [comment]
@itkonen onko tälle jotain ratkaisua? Se estää meidän datojen päivityksen.

**Comment by itkonen** [comment]
Nykyisellä palvelinversiolla tämän pitäisi toimia. Luken tietokanassa on jonkin verran ollut puutteellisia metatietoja, mutta nyt parsereita on terästetty.
