### ISSUE TITLE
Ongelmia yhteydessä

### ISSUE THREAD

**Issue by jhuovari** [robonomist/robonomistClient#20]
Viimeaikoina on ollut ajoittain ongelmia hakea dataa. Esim:

- Monesti ensimmäisellä kerralla haku johtaa virheeseen, mutta sama haku uudelleen toimi.
- Tänään vakkan build failasi eia:n sarjaan. Myöskään data("eia/") ei löytänyt mitään. Kokeilin data("EIA/") ja se toimi ja sen jälkeen myös  alkuperäinen haku pienillä kirjaimilla.

**Comment by jhuovari** [comment]
Nyt data("fao/QCL") antaa vain virheen. Aiemmin toimi ja osa fao tauluista näyttäisi toimivan ja osa ei.
@itkonen

**Comment by itkonen** [comment]
Pahoittelut virheistä!  `"fao/QCL"` on hävinnyt FAO:n palvelimelta vaika se löytyy yhä sisällysluettelosta. Myös joitain muita FAO:n datoja on kadonnut. Lähetin heille virheraportin.

Päivitin teidän palvelimen uusimpaan versioon ja testailen, jos saan muut virheen replikoitua. Joskus on käynyt niin, että datalähteen sisällysluettelo ei ole saatavilla, vaikka serveri yrittää sitä hakea varsin sinnikkäästi.

Pohdin, että palvelimen välimuistiin voisi luoda sellaisen asetuksen/ominaisuuden, että välimuisti tarjoaa varoituksen kera viimeisimmän toimivan version datasta, vaikka sen ajantasaisuutta ei voida varmistaa lähteeltä. Näin tarjolla olisi ainakin viimeisin versio, ei vika kaataisi koko putkea.

**Comment by itkonen** [comment]
Nyt FAO näyttäisi saaneen systeeminsä taas kuntoon. Päivitin teidän serverin, kun siellä oli muuttunut sisällysluettelo.
