### ISSUE TITLE
OECD tiva haku

### ISSUE THREAD

**Issue by jhuovari** [robonomist/robonomistClient#21]
Yritin hakea OECD:n tiva tietokannasta tietoja. Alla oleva haku ei kuitenkaan tuota kaikkia tietoja. Esim Dometic va.. Suomelle puuttuu. Tieto kuitenkin löytyy ja sen saa rajoittamalla haun Industry == "TOTAL", mutta kuin tarvisin ne kaikki. 

Muuta rajoitusta en saanut toimimaan. Maa-filtteröinti antaa: "Error: Filtering expressions must contain exactly one table variable."
ja aika tiputtaa kaikki havainnot pois.

```
pdat_va_ind <- 
  robonomistClient::data_get("oecd/TIVA_2021_C1", tidy_time = TRUE) |> 
  filter(Indicator %in% c("Value added", "Domestic value added embodied in foreign final demand"),
         # time == "2018-01-01"
                # "Country / Region" %in% c("Finland",  "Euro area (19 countries)"),
                # "Partner country / region" %in% c("Russian Federation", "World")
                # Industry == "TOTAL"
         ) |> 
  collect()
```

@itkonen

**Comment by itkonen** [comment]
Tämä bugi on nyt fixattu robonomistClietin versiossa 2.2.1.

**Comment by jhuovari** [comment]
Pyystyykö niitä / sisältäviä sarakkeita filteröimään jollain tavalla?

**Comment by jhuovari** [comment]
Uusi versio ei vielä masterissa ?

**Comment by itkonen** [comment]
Anteeksi virheeni, uusi versio oli tosiaan jäänyt puskematta. Nyt pitäisi olla.
