### ISSUE TITLE
Datapyyntö USDAn kv-dataa 

### ISSUE THREAD

**Issue by pskinnun** [robonomist/robonomistClient#22]
Pystyykö saamaan USDA:n PSD-online palvelun tietoja? Ainakin viljoille (vehnä, maissi) sekä soijalle kv-arvot (World total) Area harvested ja Production muuttujat olisi hyvä.  

Portaali löytyy täältä https://apps.fas.usda.gov/psdonline/app/index.html#/app/home. Ainakin jotain bulkkilatausta ja API-queryjä näyttäis tarjoavan.

**Comment by itkonen** [comment]
Joo, tämä oli helppo lisätä. Datan saa tällä: 
`data("tidy/usda_psd")` 

Datasetissä on kolme aika-muuttujaa: Calendar_Year, Market_Year ja Month. Näistä voisi muodostaa date-luokan aikaulottuvuusmuuttujan, mutta en tiedä, kumpi vuosi-muuttujista on relevantti. Jos sellainen on tarpeen, voin lisätä sen vielä tuohon datatauluun.

**Comment by pskinnun** [comment]
Market_Year näyttäisi olevan vuosi, jota tiedot koskevat. Aikaulottuvuus olisi hyvä niin ei ei tarvitse sitä itse aina koostaa siihen.

**Comment by itkonen** [comment]
Jes, nyt löytyy `data("tidy/usda_psd_v2")`, jossa on aikaulottuvuus siistitty valmiiksi. Osasta havainnoista puuttuu Month-tieto, joten ne on merkattu vuosimuuttujiksi (ks. Frequency-sarake).
