### ISSUE TITLE
Viikkodatan päivämäärä isoweek mukaan

### ISSUE THREAD

**Issue by jhuovari** [robonomist/robonomistClient#23]
Viikkodata saattaa tulla nyt edellisen viikon päivämäärälle. esim "luke/02_Maatalous/06_Talous/04_Maataloustuotteiden_EU-hintaseuranta/02_Viljan_hinnat_EU.px"
Luulen että kysessä week() ja isoweek() ero. isoweek:llä tulee oikein.

**Comment by itkonen** [comment]
Uudessa versiossa tämä on fiksattu, ja päivitin juuri teidän palvelimen. Nuo viikkomerkinnät vähän hankalia, kun lähteet käyttävät välillä vähän mitä sattuu. Mutta px-pohjaisissa datoissa on nyt ISO-viikko. 

Btw. uuteen versioon tuli uutena datalähteen Bundesbank (rajapinta tosin on vähän hankala kuten EKP:llä). Ks. `data("bundesbank/")`

Huom. myös uusi tidy-taulu, jossa on komission keräämiä polttoainehintoja viikoittain: `data("tidy/ec_oil_bulletin")`

**Comment by jhuovari** [comment]
Hyvä kiitos. Maailmassa tehdä samoja asioita harmillisen paljon eri tavoilla :). 
Hyvä tietää uudet lähteet.
