### ISSUE TITLE
Luken time ongelmia

### ISSUE THREAD

**Issue by jhuovari** [robonomist/robonomistClient#24]
Lisää ongelmia luken time:n parsinnassa:

"luke/04_Metsa/02_Rakenne_ja_tuotanto/06_Puun_markkinahakkuut/04_Vuositilastot/01a_Teollisuuspuun_hakkuut_maak_v.px"

vuositieto, jossa tidy_time ei tule oikein.

**Comment by itkonen** [comment]
Tämä on nyt fiksattu Luken päässä, joten aikamuuttuja tulee oikein.
