### ISSUE TITLE
Tullin tidy

### ISSUE THREAD

**Issue by jhuovari** [robonomist/robonomistClient#25]
tidy/tulli_indeksit ei jostaan syystä toimi. Antaa vain virheen.

Voisiko tehdä myös tidy-taulun, jossa on yhdistetty ennakkotieto ja historiatieto? Kokonaisvienti ja -tuonti jatkettuna uljas_ennakko -tiedolla. Samaan voisi laske myös volyymisarjat deflatoituna vienti- ja tuontihintaideksillä?

**Comment by itkonen** [comment]
"tidy/tulli_indeksit" on nyt korjattu. Tullin rajapinnassa oli joitain rikkovia muutoksia, jotka sotkivat muutamia datatauluja.

Ennakkotiedolla jatkettu historia löytyy nyt täältä: `data("tidy/tulli_ennakko")`. 

Esimerkki:
```
data_get("tidy/tulli_ennakko") |>
  ggplot(aes(time,value, color = Suunta)) +
  geom_line() +
  facet_wrap(~Maaryhmä)
```
