### ISSUE TITLE
Datapyyntö: World bank commodity prices

### ISSUE THREAD

**Issue by pskinnun** [robonomist/robonomistClient#26]
Jos mahdollista, tämä world bankin hyödykkeiden hintatiedot olisi hyvä lisä datoihin. Linkki julkasupaikkaan https://www.worldbank.org/en/research/commodity-markets  ja sit itse kuukausitason dataan https://thedocs.worldbank.org/en/doc/5d903e848db1d1b83e0ec8f744e55570-0350012021/related/CMO-Historical-Data-Monthly.xlsx (en tiedä onko vaihtuuko toi datan linkki kuukausittain). Taulukko päivittyy pääsääntöisesti aina kuukauden toisen arkipäivänä.

**Comment by itkonen** [comment]
Jes, nyt hintatiedot löytyvät haulla `data("tidy/pink_sheet")`. Ovatko ne siinä muodossa kuin toivoisit?

**Comment by pskinnun** [comment]
Jes, tämä on hyvä!
