### ISSUE TITLE
Datapyyntö: Bensan hinta

### ISSUE THREAD

**Issue by jhuovari** [robonomist/robonomistClient#28]
Kaipaisimme bensan viikkohintoja.
Meillä oli aiemmin dataa lähteenä dg ecfin, mutta en kyllä löydä mikä datalähde se olisi.
Komissiolla on kyllä Weekly oil bulletin: https://energy.ec.europa.eu/data-and-analysis/weekly-oil-bulletin_en
ja siellä on kyllä tarvittava data (veroton ja verollinen E95) : https://ec.europa.eu/energy/observatory/reports/Oil_Bulletin_Prices_History.xlsx , mutta voi hyvää päivää tuon excelin kanssa. Miksi ihmeessä dataa jaetaan tuossa muodossa.
Onko ajatuksia voisiko löyty jostain helpompi lähde?
Tilastokeskuksellahan on Suomesta dataa, mutta se on kuukausi.

**Comment by itkonen** [comment]
Bensan viikkohinnat löytyvät täältä: `data("tidy/ec_oil_bulletin")` Siellä on verolliset ja verottomat hinnat samassa taulukossa. 

Komissiolla on tosiaan aika erikoinen tapa jakaa dataa, ja näiden kanssa on saanut taistella melkoisen tovin, jotta tiedot on saanut siistittyä ja ladattua luotettavasti. Varmasti ovat käyttäneet paljon vaivaa, että ovat saaneet kerättyä näin hienon datasetin, mutta on outoa, että sitä jaetaan tällä tavalla.

**Comment by jhuovari** [comment]
Kiitos, sehän oli nopeasti toimittu.
