### ISSUE TITLE
tidy/10yield ei päivity

### ISSUE THREAD

**Issue by jhuovari** [robonomist/robonomistClient#29]
Viimeisin havainto: 2022-03-11

**Comment by itkonen** [comment]
Taulukko päivittyy nyt muiden maiden osalta paitsi Suomen. Tässä on ongelmana, että tietoja ei ole saatavilla helposti koneluettavassa muodossa, vaan ne pitää hakea selainautomaatiolla. Käytännössä siis robotin pitää matkia selainta käyttävää ihmistä. Meillä työnalla infra, jolla saamme näitä kaikkein hankalimpia tiedonhakuja automatisoitua helposti, eli lähitulevaisuudessa näidenkin pitäisi päivittyä.
