### ISSUE TITLE
Datapyyntö UNCTAD

### ISSUE THREAD

**Issue by jhuovari** [robonomist/robonomistClient#3]
Voisiko UNCTAD:n tilastot lisätä tietokantaa?
http://unctadstat.unctad.org/EN/BulkDownload.html

**Comment by itkonen** [comment]
Lisäsin UNCTAD:n tietokantaan ja päivitin teidän palvelimen. Komennolla `data("unctad/")` saat listauksen taulukoista.

**Comment by jhuovari** [comment]
Sehän oli nopea, kiitos.
