### ISSUE TITLE
Tietopyyntö: Valtiontalouden kuukaisitiedot

### ISSUE THREAD

**Issue by jhuovari** [robonomist/robonomistClient#30]
Kaipaisin Valtiokonttorin tietoja valtiontaloudesta kuukausittain. Tietoja on kuukausikatsauksessa: https://www.tutkihallintoa.fi/valtio/taloustiedot/valtiontalouden-kuukausikatsaus, mutta nykyyään kai myös avoimen rajapainnan kautta: https://avoindata.tutkihallintoa.fi/.
Siellähän on sitten myös kaikenlaista muutakin tieto ja myös kuntadataa.
@itkonen

**Comment by itkonen** [comment]
Valtiokonttorin rahavirtalaskelman saa nyt tällä `data("tidy/valtiontalouden_rahavirtalaskelma")`.

Tutkihallintoa.fi:n integraatiot ovat nyt testausvaiheessa ja tulevat seuraavan päivitykseen eli ihan pian.

**Comment by jhuovari** [comment]
Kiitos. Toimii hyvin ja kuulostaa oikein hyvältä tuo tutkihallintoa lisääminen.

**Comment by itkonen** [comment]
Noniin, nyt löytyy myös tutkihallintoa.fi-palvelun datoja teidän palvelimelta: `data("tutkihallintoa/")`. Siellä on budjettitalouden tapahtumat ja valtion henkilöstön tiedot kokonaisina taulukoina.
