### ISSUE TITLE
eia:n datat ei toimi

### ISSUE THREAD

**Issue by jhuovari** [robonomist/robonomistClient#32]
Haut antavat vain virhettä. Ainakin:
data_get("eia/PET")
data_get("eia/NG"
@itkonen

**Comment by itkonen** [comment]
EIA on uusinut API:nsa ja vanhan version, jossa olemme kiinni, olisi vielä pitänyt toimia, mutta näköjään se on mennyt rikki. Meidän pitää siis vaihtaa uuteen API:iin saman tien. Korjaamme tämän asap.
