### ISSUE TITLE
datapyyntö: Energiaviraston sähkön hinnat

### ISSUE THREAD

**Issue by pskinnun** [robonomist/robonomistClient#34]
Onko mahdollista saada mukaan Energiaviraston sähkön hintatilastot: [https://energiavirasto.fi/sahkon-hintatilastot](https://energiavirasto.fi/sahkon-hintatilastot). Sieltä ainakin noi aikasarjat tarjoushinnoista ja sähkön toimitusvelvollisuus- ja siirtohintojen kehityksestä voisivat olla hyödyllisiä.

**Comment by itkonen** [comment]
Nyt on uudessa serveri-versiossa mukana myös Energiaviraston tilastoja: `data("energiavirasto/")`
