### ISSUE TITLE
unctad ongelma vielä jatkuu, elokuun ja syyskuun tiedot ovat jääneet päivittymättä.

### ISSUE THREAD

**Issue by pskinnun** [robonomist/robonomistClient#38]
Tämä ongelma vielä jatkuu, elokuun ja syyskuun tiedot ovat jääneet päivittymättä.

_Originally posted by @pskinnun in https://github.com/robonomist/robonomistClient/issues/35#issuecomment-1808124090_

**Comment by itkonen** [comment]
Korjattu, ja palvelimet päivtetty! Nyt pitäisi taas toimia.
