### ISSUE TITLE
dl_filter käyttö?

### ISSUE THREAD

**Issue by jhuovari** [robonomist/robonomistClient#4]
Miten `data`-function dl_filter:ä voi käyttää? Yritän hakea 12 kk euriboria ECB:ltä. En oikein keksi miten sieltä saa järjellisen määrän data tai dataa ylipäätään.
@itkonen

**Comment by itkonen** [comment]
Lisäsin dokumentaatiota dl_filterin käytöstä tänne: https://robonomist.github.io/robonomistClient/reference/data.html

Tässä on pari vaihtoehtoa, joilla euriborit voi hakea:

data(
   "ecb/FM",
   dl_filter = list(freq = "M",
                    provider_fm_id = "EURIBOR1YD_")
 )
 data("ecb/FM", dl_filter = "M.U2.EUR.RT.MM.EURIBOR1YD_.HSTA")

Valitettavasti EKP:n rajapinta on poikkeuksellisen hankala ja hidas. Osin hitaus liitty olemassa oleviin parsereihin, mutta suunnitelmissa on koodata omat data-hakujen nopeuttamiseksi.

**Comment by jhuovari** [comment]
Kiitos. Tuo EKP:n tietokanta on kyllä hankala ja sieltä oikean tiedon löytäminen kiven takana.

**Comment by jhuovari** [comment]
Mitenkäs vastaava toimii Tullille?

**Comment by itkonen** [comment]
Tässä on yksi esimerkki datahausta:
```
 data("tulli/uljas_cpa2008",
      dl_filter = list("Tavaraluokitus CPA2008_2" = "*A-X",
                       "Aika" = c("201505", "201506"),
                       "Maa" = "=ALL",
                       "Suunta" = "=FIRST 1",
                       "Indikaattorit" = "=FIRST 1"))
```
Toistaiseksi käyttöä vaikeuttaa se, että API:sta haettavien rivien määrä on rajallinen. Tähän on suunnitelmissa koodata haunpalastelija, jottei käyttäjän tarvitsisi tästä murehtia.

**Comment by jhuovari** [comment]
Kiitos. 

Tullin tiedoista voisi olla kätevää valmiit yksinkertaisemmat taulut keskeisistä tiedoista. Näin ekonomistille siellä on vähän liikaa dataa.

**Comment by itkonen** [comment]
Totta! Voin tehdä valmiita tidy-taulukkoja, jos lähetät listan tiedoista, joita tarvitsette. Vissiin perus vienti- ja tuontiaggregaatit, mutta olisiko muita?

**Comment by itkonen** [comment]
Uusimmassa data serverissä on nyt Tulli-datoille haunpalastelija, joten nyt käyttäjän ei tarvitse välittää API:n rajoitteista.

Uutena ominaisuutena filteristä voi jättää vapaasti dimensioita määrittämättä, jolloin haetaan kaikki datat. Ääriesimerkkinä voi kokeilla argumettia `dl_filter=list(NULL)`, jolloin funktio palauttaa koko kuution ensisijaisilla luokitteluilla. Useimmissa tapauksissa koko kuution lataus saattaa kestää tuskallisen kauan.

Lisäksi kokosin valmiiksi joitain rajatumpia näkymiä tänne: `data("tidy/tulli")`

**Comment by jhuovari** [comment]
Luulen, että noi tidy-datat riittää meillä lähes aina. Kiitos.
