### ISSUE TITLE
Aineistopyyntö: Kuntien ja kuntayhtymien talous (tutkihallintoa.fi)

### ISSUE THREAD

**Issue by pskinnun** [robonomist/robonomistClient#41]
Onko mahdollista lisätä kuntien ja kuntayhtymien talous -tiedot tutkihallintoa.fi -sivustolta. AInakin osa tutkihallintoa-tietoja näyttää olevan. Rajapintakin on olemassa näihin tietoihin.  

vrt. https://www.tutkihallintoa.fi/kunnat/kuntien-ja-kuntayhtymien-talous/#mita-taloustietoja-kunnat-raportoivat

**Comment by itkonen** [comment]
Olemme pitkään selvitelleet näitä kuntatilastojen saatavuutta, ja tällä hetkellä Valtiokonttori tarjoaa kuntatalouden osalta rajapintoina vain taksonomiat ja rekisteritietokannan, mutta varsinaiset tilastot on tarjolla vain PowerBI-sovellusten kautta. PowerBI:ssä tietojen hakeminen koneellisesti on tehty tarkoituksella hyvin hankalaksi, kun kaiketi käyttö on haluttu rajata ihmisten käytettäväksi manuaalisesti. Rekisteritietokannasta periaatteessa löytyy taloustiedot, mutta ne ovat siis tapahtumatason kirjanpitotietoja kaikista kuntasektorin y-tunnuksista. Dataa on siis valtavasti ja vaatisi suuren työn (taksonomioiden ja y-tunnusten yhdistelyä), jotta niistä saisi yleistason tietoa, kuten sitä on esitetty PowerBI-raporteissa. Kuuleman mukaan tiedoissa on myös paljon virheitä, joiden oikominen on työlästä ja vaatisi erityisasiantuntemusta.

Käytännössä siis luulen, että paras olisi patistaa Valtiokonttoria julkaisemaan rekistereistä johdetut tilastot rajapinnan kautta, jotta ne voitaisiin ottaa haltuun tehokkaasti.
