### ISSUE TITLE
Datapyyntö DG agri

### ISSUE THREAD

**Issue by jhuovari** [robonomist/robonomistClient#5]
Maidon hinta pitäisi vielä tietä :)
Voisiko saada DG agrin hinta dashboardin tiedot: https://agridata.ec.europa.eu/extensions/DashboardPrice/DashboardMarketPrices.html#

Tarjoavat kaikki tiedot yhdessä csv:ssä Bulk downloadin alla. 

Tällä ei ole kovin kiire.

**Comment by itkonen** [comment]
Maidon hinta löytyy nyt täältä: `data("tidy/dg_agri")`

**Comment by jhuovari** [comment]
Pitääkö päivittää joitain? Ei näy tidyssa.
