### ISSUE TITLE
ECB:n tietokannasta value on character

### ISSUE THREAD

**Issue by jhuovari** [robonomist/robonomistClient#6]
ECB:n tietokannasta value tulee nyt character muodossa ei numero. Toimi aikaisemmin, mutta nyt muuttunut.

Esim:
`data_get("ecb/FM", dl_filter = "M.U2.EUR.RT.MM.EURIBOR1YD_.HSTA") |> str()`
@itkonen

**Comment by jhuovari** [comment]
Tähän liittyi, että ensi haku ei toiminut ollenkaan ja sen jälkeen hetken mitkään haut eivät toimineen.

**Comment by itkonen** [comment]
Vika löytyi rsdmx paketista, joka on oikutellu viime aikoina. Jostain syystä se raksuttaa sdmx-metadatoja tuhottoman kauan. Meinaan poistaa sen riippuvuuksista kokonaan ja parsia metadatat suoraan xml:llä. Fixin tekemiseen ei pitäisi mennä kauaa.

**Comment by itkonen** [comment]
Uusimmasta serveristä (v2.4.13) oikutellut rsdmx-paketti on kirjoitettu pois. Tilalla on nyt oma sdmx-parseri, joka on vieläpä noin mittaluokan verran aimpaa nopeampi. 

Nyt myös kokonaisia tauluja on mahdollista ladata, jos ne vain mahtuvat koneen muistiin: `dl_filter = list(NULL)`

Uudessa versiossa tuli sellainen pieni rikkova muutos, että ECB-data tulevat nyt oletuksena selkokielisillä muuttujanimillä. Ne saa halutessaan pois päältä argumentilla `variable_labels = FALSE`.

**Comment by jhuovari** [comment]
Nyt toimii, kiitos
